version: "3.3" # version of compose format

services:
  landing-service:
    build: ./landing # path is relative to docker-compose.yml location
    hostname: landing-service
    ports:
      - 5050:5050 # host:container
    networks:
      sample:
        aliases:
          - landing-service
  # Add more services below
  addition:
    build: ./addition
    ports:
      - 5059:5059
    networks:
      sample:
        aliases:
          - addition
  bitwiseand:
    build: ./bitwiseand
    ports:
      - 5060:5060
    networks:
      sample:
        aliases:
          - bitwiseand
  divide:
    build: ./divide
    ports:
      - 5056:5056
    networks:
      sample:
        aliases:
          - divide
  multiply:
    build: ./multiply
    ports:
      - 5057:5057
    networks:
      sample:
        aliases:
          - multiply  
  sumofsquare:
    build: ./sumofsquare
    ports:
      - 5053:5053
    networks:
      sample:
        aliases:
          - sumofsquare   
  average:
    build: ./average
    ports:
      - 5052:5052
    networks:
      sample:
        aliases:
          - average  
  modulus:
    build: ./modulus
    ports:
      - 5051:5051
    networks:
      sample:
        aliases:
          - modulus 
  minus:
    build: ./minus
    ports:
      - 5058:5058
    networks:
      sample:
        aliases:
          - minus
networks:
  sample:
